
const students = {            
    'Bus 01': [ 
   { register: "01   11D", name: "T. Romindu Tharaka Munasinghe" },
  { register: "02   11D", name: "K. A. Abhiru Dewasara" },
  { register: "03   11D", name: "M. A. Tharush Kavishan" },
  { register: "04   11D", name: "S. Sehansa Ranasinghe" },
  { register: "05   11D", name: "E. A. D. Boditha Jananandith" },
  { register: "06   11D", name: "R. M. T. Senuth Rajapaksha" },
  { register: "07   11D", name: "Kaniskha Vishwadinu Herath" },
  { register: "08   11D", name: "P. L. Sethum Sethwin" },
  { register: "09   11D", name: "A. B. Sadik Sathsilu" },
  { register: "10   11D", name: "D. Videv Mindula" },
  { register: "11   11D", name: "A. P. Janindu Nimsara" },
  { register: "12   11D", name: "U. D. Yashod Sandesh" },
  { register: "13   11D", name: "A. Hasara Pathirana" },
  { register: "14   11D", name: "K. L. Geeneth Sasvidu" },
  { register: "15   11D", name: "B. J. Nethum Netsara" },
  { register: "16   11D", name: "U. S. Sathik Haminsana" },
  { register: "17   11D", name: "U. J. Chathil Kariyawasam" },
  { register: "18   11D", name: "D. S. H. Imal Tharushika" },
  { register: "19   11F", name: "W. Anuga Vihas" },
  { register: "20   11F", name: "K. K. Chamik Kavithra" },
  { register: "21   11F", name: "D. G. Nomith Yuthmith" },
  { register: "22   11F", name: "U. O. H. S. Udugampola" },
  { register: "23   11F", name: "Rusiru Ranmina Wellala" },
  { register: "24   11F", name: "E. Anuhas Manuga" },
  { register: "25   11F", name: "W. M. Sandalu Yashintha" },
  { register: "26   11F", name: "A. G. Dulen Yehens" },
  { register: "27   11F", name: "A. V. Kaushika Tharumina" },
  { register: "28   11F", name: "Dulsadu Senuth Gajanayake" },
  { register: "29   11F", name: "I. Pracheera Chethana" },
  { register: "30   11F", name: "L. V. D. Amod" },
  { register: "31   11F", name: "M. D. Jeram Shamika" },
  { register: "32   11F", name: "G. H. P. A. W. Piyumal" },
  { register: "33   11F", name: "K. V. Malitha Madhushan" },
  { register: "34   11F", name: "M. K. Omith Damyuru" },
  { register: "35   11F", name: "Risika Nethyuru" },
  { register: "36   11F", name: "L. V. D. Chamod Rashmika" },
  { register: "37   11F", name: "L. Methuka Manhiru" },
  { register: "38   11F", name: "T. W. Bisath Manumika" },
  { register: "39   11F", name: "Randul De Soysa" },
  { register: "40   11F", name: "A. H. Ashen Chathuranga" },
  { register: "41   11F", name: "S. A. Kenod Hiruk" },
  { register: "42   11F", name: "H. K. A. Devmika" },
  { register: "43   11F", name: "K. G. Dinana Sevhas" },
  { register: "44   11F", name: "Soniru Sandes" },
  { register: "45   11F", name: "N. D. N. Sesith" },
  { register: "46   11F", name: "Yonal Nethmika" },
  { register: "47   11F", name: "Uvindu Chiran Mahendra" },
  { register: "48   11F", name: "W. K. M. Sadik" },
  { register: "49   11F", name: "K. L. S. Mathish" },
  { register: "50   11F", name: "H. V. Yugith Damyuru" }
],

    'Bus 02': [{ register: "01   11A", name: "K. K. G. Mithun Maheesha" },
  { register: "02   11A", name: "G. Sandila Bonuka" },
  { register: "03   11A", name: "D. Lithum Ambepitiya" },
  { register: "04   11A", name: "H. A. Manaram Thathsara" },
  { register: "05   11A", name: "J. Ruvindu Hansana" },
  { register: "06   11A", name: "K. B. O. T. Sankalana" },
  { register: "07   11A", name: "W. G. Helajith Dinujaya" },
  { register: "08   11A", name: "K. P. Thinur Dinsath" },
  { register: "09   11A", name: "G. W. S. H. D. Sahaspathi" },
  { register: "10   11A", name: "W. M. Senula Dharmapath" },
  { register: "11   11A", name: "M. K. Isara" },
  { register: "12   11A", name: "D. R. Methul Dahanayake" },
  { register: "13   11A", name: "B. Binuka Chamisha Dahanayake" },
  { register: "14   11A", name: "W. E. A. K. Naveen Kaniska" },
  { register: "15   11A", name: "W. H. Biman Basilu" },
  { register: "16   11A", name: "D. H. K. A. Prasanjana" },
  { register: "17   11A", name: "H. S. Nimsara Thilakarathna" },
  { register: "18   11A", name: "G. H. A. Akash Denuwan" },
  { register: "19   11A", name: "M. H. Kesara Buddhamal" },
  { register: "20   11A", name: "G. W. Theruk De Silva" },
  { register: "21   11A", name: "L. A. K. Dilshan" },
  { register: "22   11A", name: "B. H. Sethik Dinsara" },
  { register: "23   11A", name: "A. A. Senith Dinsara" },
  { register: "24   11A", name: "M. G. Aken Yensith" },
  { register: "25   11A", name: "P. D. Ganindu Deneth" },
  { register: "26   11A", name: "M. H. I. Devdunu" },
  { register: "27   11A", name: "O. Theon Helik" },
  { register: "28   11D", name: "D. Theshika Gamage Yatagama" },
  { register: "29   11D", name: "Adil Rankindu Pasqual" },
  { register: "30   11D", name: "D. B. Minuk Hiranya" },
  { register: "31   11D", name: "A. H. Senura Jayashan" },
  { register: "32   11D", name: "N. H. W. N. Shashin Jayathunga" },
  { register: "33   11D", name: "B. G. Lakindu Netsara" },
  { register: "34   11D", name: "H. Pamod De Soysa" },
  { register: "35   11D", name: "K. E. A. Chandupa Abhiman" },
  { register: "36   11D", name: "A. G. Achintha Devmina" },
  { register: "37   11D", name: "H. K. Shrayan Patali" },
  { register: "38   11D", name: "N. P. T. Nihindu Chathnula" },
  { register: "39   11D", name: "T. G. Vinuja Nethmin" },
  { register: "40   11D", name: "H. M. Chanthuk Muthumal" },
  { register: "41   11D", name: "L. G. Thasmith Dinethmith" },
  { register: "42   11D", name: "M. A. Vinuk Senith" },
  { register: "43   11D", name: "B. G. Sinura Sasvidu" },
  { register: "44   11D", name: "K. G. Nethul Mandil" },
  { register: "45   11D", name: "J. L. Thujan Venuj" },
  { register: "46   11D", name: "I. Manith Rajapaksha" },
  { register: "47   11D", name: "P. V. A. Umayanga Malinda" },
  { register: "48   11D", name: "D. K. S. Sandaruwan De Silva" },
  { register: "49   11D", name: "R. H. Sithum Dulmira" }],
  
    'Bus 03': [
  { register: "01   11D", name: "Chamath Pasindu Lyanage" },
  { register: "02   11D", name: "Saniru Tuduwage" },
  { register: "03   11D", name: "U. P. G. Maleesh Mandil" },
  { register: "04   11D", name: "P. Madushan" },
  { register: "05   11D", name: "S. Leon Patinot" },
  { register: "06   11D", name: "R. T. Thikshana" },
  { register: "07   11D", name: "Dinal Ravin Pandith" },
  { register: "08   11D", name: "K. P. Punar Promod" },
  { register: "09   11D", name: "H. A. Rashintha" },
  { register: "10   11D", name: "H. W. Chanuga Nethvidu" },
  { register: "11   11D", name: "K. H. S. Henula" },
  { register: "12   11D", name: "J. K. J. Basith" },
  { register: "13   11D", name: "A. G. G. Nimdinu" },
  { register: "14   11D", name: "P. A. S. V. M. Abhilash" },
  { register: "15   11D", name: "K. G. Gagul Induwara" },
  { register: "16   11E", name: "Pahan Binupa" },
{ register: "17   11E", name: "Sanmith Suhaswin" },
{ register: "18   11E", name: "Yuthik Dasamsara" },
{ register: "19   11E", name: "Sasane Devmith" },
{ register: "20   11E", name: "Sathvind Wonal" },
{ register: "21   11E", name: "Shashintha Kanchana" },
{ register: "22   11E", name: "Tinal Pramukha" },
{ register: "23   11E", name: "Siluna Randiv" },
{ register: "24   11E", name: "Ulindu Pahesara" },
{ register: "25   11E", name: "R. Shan Indupa" },
{ register: "26   11E", name: "Dhanuj Senumith" },
{ register: "27   11E", name: "Osada Gayanthaka" },
{ register: "28   11E", name: "Saniru Diyath" },
{ register: "29   11E", name: "Thisal Attanayake" },
{ register: "30   11E", name: "Denuvan Punchihewa" },
{ register: "31   11E", name: "Venuk Damsara" },
{ register: "32   11E", name: "Nethma Nallaperuma" },
{ register: "33   11E", name: "Senila Hansana" },
{ register: "34   11E", name: "Sithuk Methdin" },
{ register: "35   11E", name: "Chanid Shaluka" },
{ register: "36   11E", name: "Yenuk Dulin" },
{ register: "37   11E", name: "Kisara Kalmera" },
{ register: "38   11E", name: "Sethindu Damsas" },
{ register: "39   11E", name: "Nimsara Gimhan" },
{ register: "40   11E", name: "Gimsara Yasaru" },
{ register: "41   11E", name: "Randesh Nuvaneth" },
{ register: "42   11E", name: "Videvi Winsara" },
{ register: "43   11E", name: "Senuwar Dinudik" },
{ register: "44   11E", name: "Aken Kulatunga" },
{ register: "45   11E", name: "Senuk Nimsara" },
{ register: "46   11E", name: "Sanul Nethmera" },
{ register: "47   11E", name: "Suvin Sasvidu" },
{ register: "48   11E", name: "Chamindu Dineth Nimsilu" },
{ register: "49   11E", name: "Savindu Nethmika" },
{ register: "50   11E", name: "Sanith Netharu" },
{ register: "51   11E", name: "Vihanga Sonal" },
{ register: "52   11E", name: "Sedev Dinuvara" },
{ register: "53   11E", name: "Didul Bimsara" },
{ register: "54   11E", name: "Hansaka Pathmin" },
{ register: "55   11E", name: "Dasas Ranthus" },
{ register: "56   11E", name: "Sihas Kumulitha" }
],

    'Bus 04': [{ register: "01   11B", name: "H. Amod Indupa" },
{ register: "02   11B", name: "G. K. Apsar Sansith" },
{ register: "03   11B", name: "L. G. Okindu Wathmera" },
{ register: "04   11B", name: "A. K. Ashen Shavindu" },
{ register: "05   11B", name: "Yashod Lasal Lokuge" },
{ register: "06   11B", name: "E. D. Loshith Pabasara" },
{ register: "07   11B", name: "Shakthi Ashen Sanjaya" },
{ register: "08   11B", name: "W. Janith Nimsara" },
{ register: "09   11B", name: "G. K. Thasith Thanuwara" },
{ register: "10   11B", name: "N. A. Chanuga Hansana" },
{ register: "11   11B", name: "U. A. Hasod Himakara" },
{ register: "12   11B", name: "R. H. A. Rasira Hansitha" },
{ register: "13   11B", name: "K. H. Rashith Oshada" },
{ register: "14   11B", name: "B. K. M. Maheem Kushan" },
{ register: "15   11B", name: "K. E. A. Navidu Sivhas" },
{ register: "16   11B", name: "N. D. Wanniarchchi" },
{ register: "17   11B", name: "K. Minindu Desadula" },
{ register: "18   11B", name: "Danindu Dilhara" },
{ register: "19   11B", name: "Adip Eshaan" },
{ register: "20   11B", name: "Adil Insada Vithanawasam" },
{ register: "21   11B", name: "Risindu Basilu" },
{ register: "22   11B", name: "Gagul Kethaka" },
{ register: "23   11B", name: "Abhiman Jayasinghe" },
{ register: "24   11B", name: "Thisum Jalitha" },
{ register: "25   11B", name: "H. P. Chanuka Senevirathna" },
{ register: "26   11B", name: "W. S. Thisum Dilsara" },
{ register: "27   11B", name: "G. K. Dithira Yugith" },
{ register: "28   11B", name: "K. J. Udugampola" },
{ register: "29   11B", name: "G. Avishka Udupila" },
{ register: "30   11B", name: "M. G. Sanuj Sithumdith" },
{ register: "31   11B", name: "K. K. M. T. Kodituwakku" },
{ register: "32   11B", name: "Rakmith Samarawiraarachchi" },
{ register: "33   11B", name: "Kalana Sandeepa" },
{ register: "34   11C", name: "G. P. Sandesh Netsara" },
{ register: "35   11C", name: "Saviru R. Akurugoda" },
{ register: "36   11C", name: "N. W. A. L. Sanviru" },
{ register: "37   11C", name: "G. P. A. Sandeepa" },
{ register: "38   11C", name: "Sandira Arambewela" },
{ register: "39   11C", name: "H. R. S. Thehan" },
{ register: "40   11C", name: "I. Himal Veerathunga" },
{ register: "41   11C", name: "S. A. O. Senith Pinsara" },
{ register: "42   11C", name: "B. D. Adish Deshapriya" },
{ register: "43   11C", name: "Binara W. Veerasekara" },
{ register: "44   11C", name: "Viduravi Nadeeja" },
{ register: "45   11C", name: "G. H. H. Rukshan" },
{ register: "46   11C", name: "K. D. A. Anuhas" },
{ register: "47   11C", name: "K. W. S. Yanul" },
{ register: "48   11C", name: "H. G. T. Chanketh" },
{ register: "49   11C", name: "G. V. Dinal Senumith" },
{ register: "50   11C", name: "Hirun Jayawardhana" },
{ register: "51   11C", name: "Kaveesh Githmal" }
]   
};
